theme: jekyll-theme-slate
tagline: CTO at Magenic, creator of CSLA .NET, author, speaker
author :
  name : Rockford Lhotka
  github : rockfordlhotka
  twitter : rockylhotka
  feedburner : RockfordLhotka
name: Rockford Lhotka
title: Rockford Lhotka
description: VP, Open Source Creator, Author, Speaker
markdown: kramdown
permalink: /:year/:month/:day/:title
plugins:
  - jekyll-sitemap
github:
  is_project_page: false
google_analytics: www.lhotka.net
adsense:
disqus:
